stages:
  - pack

variables:
  CALIBRE_VERSION: 5.17.0

appimage:
  stage: pack
  image: appimagecrafters/appimage-builder
  script:
    - appimage-builder --skip-test
  artifacts:
    paths:
      - '*.AppImage'
    expire_in: 1 week
