name: Build

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fuse libfuse2

    - name: Construct AppDir
      run: make

    - name: Get appimagetool
      run: |
        curl --location -o appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool

    - name: Make AppImage
      run: ./appimagetool build/calibre.AppDir

    - name: Upload Build Artifact
      uses: actions/upload-artifact@master
      with:
        name: Calibre-x86_64.AppImage
        path: ./Calibre-x86_64.AppImage
